'use client';

import type { JSX } from 'react';

import { ThemeProvider, ThemeScript } from '@ideasui/theme';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';

import './globals.css';
// import {ideasUIPlugin} from "@ideasui/theme";
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })
// `${geistSans.variable} ${geistMono.variable}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  // const plugin = ideasUIPlugin();
  // console.debug("🚀 ~ RootLayout ~ plugin:", plugin);
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <ThemeScript defaultTheme="light" />
      </head>
      <body className="antialiased">
        <ThemeProvider defaultTheme="light" />
        {children}
      </body>
    </html>
  );
}
