import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import { ThemeScript, ThemeSwitcher } from '@your-org/theme-switcher'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })
// `${geistSans.variable} ${geistMono.variable}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head className="dark:bg-bg-primary1">
        <ThemeScript
          themes={['light', 'dark']}
          defaultTheme="system"
          storageKey="theme"
          mode="class"
        />
        <ThemeSwitcher />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  )
}
