packages:
  - 'packages/components/*'
  - 'packages/core/*'
  - 'packages/themes/*'
  - 'packages/utils'
  - 'packages/hooks/*'
  - 'packages/**'
  - 'apps/**'
  - '!packages/core/styles-experimental'
