packages:
  - 'packages/components/*'
  - 'packages/core/*'
  - 'packages/themes/*'
  - 'packages/utils/*'
  - 'packages/hooks/*'
  - 'packages/icons/*'
  - 'packages/cli/*'
  - 'apps/*'
  - 'configs/*'
