// Auto-generated icon exports
// This file is generated by scripts/generate-icons.js
// Do not edit manually

export { ArrowRight } from './icons/arrow-right';
export { Heart } from './icons/heart';
export { Home } from './icons/home';
export { Search } from './icons/search';
export { Settings } from './icons/settings';
export { User } from './icons/user';

// Re-export types and utilities
export type { IconProps } from './types';
export { createIcon } from './createIcon';
export { DynamicIcon } from './dynamic-icon';
export { IconSet } from './icon-set';
export { useIconContext, withIconContext } from './icon-context';

// Icon names for dynamic usage
export const iconNames = [
  'arrow-right',
  'heart',
  'home',
  'search',
  'settings',
  'user',
] as const;

export type IconName = (typeof iconNames)[number];
