// Auto-generated icon exports
// This file is generated by scripts/generate-icons.js
// Do not edit manually

export { ArrowRight } from './icons/ArrowRight';
export { Heart } from './icons/Heart';
export { Home } from './icons/Home';
export { Search } from './icons/Search';
export { Settings } from './icons/Settings';
export { User } from './icons/User';

// Re-export types and utilities
export type { IconProps } from './types';
export { createIcon } from './createIcon';

// Icon names for dynamic usage
export const iconNames = [
  'arrow-right',
  'heart',
  'home',
  'search',
  'settings',
  'user',
] as const;

export type IconName = typeof iconNames[number];
