#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '../assets');
const SRC_DIR = path.join(__dirname, '../src/icons');

// Convert kebab-case to PascalCase
function toPascalCase(str) {
  return str
    .replace(/[_-](.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (char) => char.toUpperCase());
}

// Clean SVG content
function cleanSvg(svgContent) {
  return svgContent
    .replace(/width="[^"]*"/g, '')
    .replace(/height="[^"]*"/g, '')
    .replace(/stroke="[^"]*"/g, '')
    .replace(/fill="[^"]*"/g, '')
    .replace(/stroke-width="[^"]*"/g, '')
    .trim();
}

// Generate individual icon component (Lucide style)
function generateIconComponent(name, svgContent) {
  const componentName = toPascalCase(name);

  // Extract SVG content without the outer svg tag
  const svgInner = cleanSvg(svgContent)
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>$/, '')
    .trim();

  return `import React from 'react';
import type { IconProps } from '../types';

/**
 * ${componentName} icon component
 */
export const ${componentName} = React.forwardRef<SVGSVGElement, IconProps>(
  ({ size = 24, color = 'currentColor', strokeWidth = 2, className, ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      {...props}
    >
      ${svgInner}
    </svg>
  )
);

${componentName}.displayName = '${componentName}';
`;
}

// Process all SVG files
async function generateIcons() {
  // Create icons directory
  if (!fs.existsSync(SRC_DIR)) {
    fs.mkdirSync(SRC_DIR, { recursive: true });
  }

  if (!fs.existsSync(ASSETS_DIR)) {
    console.log('Assets directory not found. Please add SVG files to assets/ directory');

    return;
  }

  const svgFiles = fs.readdirSync(ASSETS_DIR).filter((file) => file.endsWith('.svg'));
  const iconNames = [];

  console.log(`Processing ${svgFiles.length} SVG files...`);

  for (const file of svgFiles) {
    const name = path.basename(file, '.svg');
    const componentName = toPascalCase(name);
    const svgPath = path.join(ASSETS_DIR, file);
    const svgContent = fs.readFileSync(svgPath, 'utf8');

    try {
      // Generate component
      const component = generateIconComponent(name, svgContent);
      const componentPath = path.join(SRC_DIR, `${componentName}.tsx`);

      fs.writeFileSync(componentPath, component);
      iconNames.push({ name, componentName });

      console.log(`✅ Generated ${componentName}`);
    } catch (error) {
      console.error(`❌ Error processing ${file}:`, error.message);
    }
  }

  // Generate main index file with all exports
  const mainIndexContent = `// Auto-generated icon exports
// This file is generated by scripts/generate-icons.js
// Do not edit manually

${iconNames
  .map(({ componentName }) => `export { ${componentName} } from './icons/${componentName}';`)
  .join('\n')}

// Re-export types and utilities
export type { IconProps } from './types';
export { createIcon } from './createIcon';

// Icon names for dynamic usage
export const iconNames = [
${iconNames.map(({ name }) => `  '${name}',`).join('\n')}
] as const;

export type IconName = typeof iconNames[number];
`;

  fs.writeFileSync(path.join(__dirname, '../src/index.ts'), mainIndexContent);

  // Generate icons index file
  const iconsIndexContent = `// Auto-generated icon re-exports
${iconNames
  .map(({ componentName }) => `export { ${componentName} } from './${componentName}';`)
  .join('\n')}
`;

  fs.writeFileSync(path.join(SRC_DIR, 'index.ts'), iconsIndexContent);

  console.log(`✅ Generated ${iconNames.length} icon components`);
  console.log('✅ Updated index files');
}

// Run the generator
generateIcons().catch(console.error);
