#!/usr/bin/env node
/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/explicit-function-return-type */

const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '../assets');
const SRC_DIR = path.join(__dirname, '../src/icons');

const DEFAULT_SIZE = 24;
const DEFAULT_STROKE_WIDTH = 2;

// Convert kebab-case to PascalCase
/**
 * Convert string to PascalCase
 * @param {string} str - Input string
 * @returns {string} PascalCase string
 */
function toPascalCase(str) {
  return str
    .replace(/[_-](.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (char) => char.toUpperCase());
}

// Convert kebab-case to kebab-case (ensure consistency)
/**
 * Convert string to kebab-case
 * @param {string} str - Input string
 * @returns {string} kebab-case string
 */
function toKebabCase(str) {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

// Clean SVG content
/**
 * Remove unnecessary attributes from SVG content
 * @param {string} svgContent - Raw SVG content
 * @returns {string} Cleaned SVG content
 */
function cleanSvg(svgContent) {
  return svgContent
    .replace(/width="[^"]*"/g, '')
    .replace(/height="[^"]*"/g, '')
    .replace(/stroke="[^"]*"/g, '')
    .replace(/fill="[^"]*"/g, '')
    .replace(/stroke-width="[^"]*"/g, '')
    .trim();
}

// Generate individual icon component (Lucide style)
/**
 * Generate React component code for an icon
 * @param {string} name - Icon name
 * @param {string} svgContent - Raw SVG content
 * @returns {string} Generated component code
 */
function generateIconComponent(name, svgContent) {
  const componentName = toPascalCase(name);

  // Extract SVG content without the outer svg tag
  const svgInner = cleanSvg(svgContent)
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>$/, '')
    .trim();

  return `import type { IconProps } from '../types';

import { forwardRef } from 'react';

const ICON_SIZE = ${DEFAULT_SIZE};
const ICON_STROKE_WIDTH = ${DEFAULT_STROKE_WIDTH};

/**
 * ${componentName} icon component
 */
export const ${componentName} = forwardRef<SVGSVGElement, IconProps>(
  ({ size = ICON_SIZE, color = 'currentColor', strokeWidth = ICON_STROKE_WIDTH, className, ...props }, ref) => (
    <svg
      ref={ref}
      className={className}
      fill="none"
      height={size}
      stroke={color}
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
      viewBox="0 0 24 24"
      width={size}
      {...props}
    >
      ${svgInner}
    </svg>
  )
);

${componentName}.displayName = '${componentName}';
`;
}

// Process all SVG files
/**
 * Main function to generate all icons
 * @returns {Promise<void>}
 */
async function generateIcons() {
  // Create icons directory
  if (!fs.existsSync(SRC_DIR)) {
    fs.mkdirSync(SRC_DIR, { recursive: true });
  }

  if (!fs.existsSync(ASSETS_DIR)) {
    console.warn('Assets directory not found. Please add SVG files to assets/ directory');

    return;
  }

  const svgFiles = fs.readdirSync(ASSETS_DIR).filter((file) => file.endsWith('.svg'));
  const iconNames = [];

  console.log(`Processing ${svgFiles.length} SVG files...`);

  for (const file of svgFiles) {
    const name = path.basename(file, '.svg');
    const componentName = toPascalCase(name);
    const fileName = toKebabCase(name); // Use kebab-case for filenames
    const svgPath = path.join(ASSETS_DIR, file);
    const svgContent = fs.readFileSync(svgPath, 'utf8');

    try {
      // Generate component
      const component = generateIconComponent(name, svgContent);
      const componentPath = path.join(SRC_DIR, `${fileName}.tsx`);

      fs.writeFileSync(componentPath, component);
      iconNames.push({ name, componentName, fileName });

      console.log(`✅ Generated ${componentName} (${fileName}.tsx)`);
    } catch (error) {
      console.error(`❌ Error processing ${file}:`, error.message);
    }
  }

  // Generate main index file with all exports
  const mainIndexContent = `// Auto-generated icon exports
// This file is generated by scripts/generate-icons.js
// Do not edit manually

${iconNames
  .map(({ componentName, fileName }) => `export { ${componentName} } from './icons/${fileName}';`)
  .join('\n')}

// Re-export types and utilities
export type { IconProps } from './types';
export { createIcon } from './create-icon';
export { DynamicIcon } from './dynamic-icon';
export { IconSet } from './icon-set';
export { useIconContext, withIconContext } from './icon-context';

// Icon names for dynamic usage
export const iconNames = [
${iconNames.map(({ name }) => `  '${name}',`).join('\n')}
] as const;

export type IconName = (typeof iconNames)[number];
`;

  fs.writeFileSync(path.join(__dirname, '../src/index.ts'), mainIndexContent);

  // Generate icons index file
  const iconsIndexContent = `// Auto-generated icon re-exports
${iconNames
  .map(({ componentName, fileName }) => `export { ${componentName} } from './${fileName}';`)
  .join('\n')}
`;

  fs.writeFileSync(path.join(SRC_DIR, 'index.ts'), iconsIndexContent);

  console.log(`✅ Generated ${iconNames.length} icon components`);
  console.log('✅ Updated index files');
}

// Run the generator
generateIcons().catch(console.error);
