name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a8198c4bff370c8506180b035930dea56dbd5288 # v5

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
