export const colors: Record<string, Record<string, string>>;
export const lightColors: Record<string, string>;
export const darkColors: Record<string, string>;
export const lightBg: Record<string, string>;
export const darkBg: Record<string, string>;
export const lightShadows: Record<string, string>;
export const darkShadows: Record<string, string>;
export const lightGradients: Record<string, string>;
export const darkGradients: Record<string, string>;
export const typeface: Record<string, string>;
export const typeScale: Record<string, [string, Record<string, string>]>;
export const animations: Record<string, string>;
export const keyframes: Record<string, string>;
