// @ts-nocheck
/* eslint-disable */
/* sonar-disable */
// Auto-generated props documentation
// Extracted from actual TypeScript interfaces
// DO NOT EDIT MANUALLY - Excluded from SonarQube duplication check

export interface PropInfo {
  name: string;
  type: string;
  required: boolean;
  defaultValue: string | null;
  deprecated: boolean;
  description: string;
}

export interface ComponentDoc {
  componentName: string;
  title: string;
  component: string;
  description: string;
  props: PropInfo[];
}

export interface PropsDocumentation {
  button: ComponentDoc[];
  buttonGroup: ComponentDoc[];
  text: ComponentDoc[];
  inputField: ComponentDoc[];
  checkbox: ComponentDoc[];
  textarea: ComponentDoc[];
}

/**
 * Components extracted from TypeScript interfaces:
 * - Button: ButtonBaseProperties, ButtonLabelProperties, ButtonIconProperties, ButtonSpinnerProperties, ButtonShortcutProperties
 * - ButtonGroup: ButtonGroupProperties
 * - Text: TextProps
 * - InputField: InputFieldProps, InputFieldLabelProps, InputFieldInputProps, InputFieldDescriptionProps, InputFieldErrorProps
 * - Checkbox: CheckboxProps, CheckboxGroupProps
 * - Textarea: TextareaProps, InputFieldTextareaProps
 */
export const propsDocumentation: PropsDocumentation = {
  button: [
    {
      componentName: 'Button',
      title: 'Button Props',
      component: '<Button />',
      description: 'Primary button component with variants and sizes',
      props: [
        {
          name: 'isLoading',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Whether the button is in a loading state.',
        },
        {
          name: 'loadingIndicator',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'The element to display as a loading indicator. If not provided, a default spinner will be used.',
        },
        {
          name: 'loadingPosition',
          type: '"start" | "end" | "center"',
          required: false,
          defaultValue: "'start'",
          deprecated: false,
          description: 'The position of the loading indicator relative to the button content.',
        },
        {
          name: 'startIcon',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Icon to display before the button content.',
        },
        {
          name: 'endIcon',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Icon to display after the button content.',
        },
        {
          name: 'shortcut',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The shortcut keys to display.',
        },
        {
          name: 'divider',
          type: '"full" | "middle" | "none"',
          required: false,
          defaultValue: "'full' (when isAttached is true)",
          deprecated: false,
          description: 'The type of divider to display between the buttons in a group.',
        },
        {
          name: 'classNames',
          type: 'ButtonClassNames',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom class names for individual button slots.',
        },
        {
          name: 'slotProps',
          type: 'ButtonSlotProps',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom props for individual button slots.',
        },
        {
          name: 'className',
          type: 'string | ((properties: ButtonRenderProps) => string)',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'The CSS class name for the button. Can be a string or a function that receives the button render props.',
        },
        {
          name: 'children',
          type: 'ReactNode | ((properties: ButtonRenderProps) => ReactNode)',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'The content to display inside the button. Can be a ReactNode or a function that receives the button render props.',
        },
        {
          name: 'isIconOnly',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Whether the button should be square and optimized for icons. Note: When true, you MUST provide an `aria-label` or `aria-labelledby` for accessibility.',
        },
        {
          name: 'aria-label',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Accessibility label for the button. Required if the button has no visible label (e.g., `isIconOnly`).',
        },
        {
          name: 'aria-labelledby',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'ID of an element that serves as the accessible label for the button.',
        },
      ],
    },
    {
      componentName: 'Button.Label',
      title: 'Button Label Props',
      component: '<Button.Label />',
      description: 'Label component inside the button',
      props: [],
    },
    {
      componentName: 'Button.Icon',
      title: 'Button Icon Props',
      component: '<Button.Icon />',
      description: 'Icon component inside the button',
      props: [
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The icon content.',
        },
        {
          name: 'placement',
          type: '"start" | "end"',
          required: false,
          defaultValue: "'start'",
          deprecated: false,
          description: 'The placement of the icon relative to the label.',
        },
      ],
    },
    {
      componentName: 'Button.Spinner',
      title: 'Button Spinner Props',
      component: '<Button.Spinner />',
      description: 'Spinner component inside the button',
      props: [
        {
          name: 'label',
          type: 'string',
          required: false,
          defaultValue: "'Loading'",
          deprecated: false,
          description: 'Accessibility label for the spinner.',
        },
      ],
    },
    {
      componentName: 'Button.Shortcut',
      title: 'Button Shortcut Props',
      component: '<Button.Shortcut />',
      description: 'Shortcut component inside the button',
      props: [
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The shortcut keys to display.',
        },
      ],
    },
  ],
  buttonGroup: [
    {
      componentName: 'Button.Group',
      title: 'Button Group Props',
      component: '<Button.Group />',
      description: 'Group component for layout of multiple buttons',
      props: [
        {
          name: 'size',
          type: "NonNullable<ButtonGroupContextType['size']>",
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The size of the buttons in the group.',
        },
        {
          name: 'color',
          type: "NonNullable<ButtonGroupContextType['color']>",
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The color scheme of the buttons in the group.',
        },
        {
          name: 'variant',
          type: "NonNullable<ButtonGroupContextType['variant']>",
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'The visual style of the buttons in the group.',
        },
        {
          name: 'isDisabled',
          type: 'boolean',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Whether the buttons in the group should be disabled.',
        },
        {
          name: 'isAttached',
          type: 'boolean',
          required: false,
          defaultValue: 'true',
          deprecated: false,
          description: 'Whether the buttons in the group should be joined together without gaps.',
        },
        {
          name: 'divider',
          type: '"full" | "middle" | "none"',
          required: false,
          defaultValue: "'full' (when isAttached is true)",
          deprecated: false,
          description: 'The type of divider to display between the buttons in the group.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          defaultValue: null,
          deprecated: false,
          description: 'The content of the button group.',
        },
      ],
    },
  ],
  text: [
    {
      componentName: 'Text',
      title: 'Text Props',
      component: '<Text />',
      description:
        'Theme-aware typography primitive supporting semantic tokens, line clamping, and slots',
      props: [
        {
          name: 'as',
          type: 'ElementType',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'The underlying HTML element or React component to render. If omitted, automatically selects the semantic element based on `variant`: - `h1`–`h6` → `<h1>`–`<h6>` - `body`, `lead` → `<p>` - `label`, `caption`, `overline`, `helper` → `<span>` - `code` → `<code>`',
        },
        {
          name: 'variant',
          type: 'TextVariant',
          required: false,
          defaultValue: "'body'",
          deprecated: false,
          description:
            'Typographic intent variant. Sets default font size, font weight, line height, and HTML tag.',
        },
        {
          name: 'size',
          type: 'TextSize',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Font size scale override. When provided, overrides the default font size scale of the active `variant`.',
        },
        {
          name: 'weight',
          type: 'TextWeight',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Font weight setting override. When provided, overrides the default font weight of the active `variant`.',
        },
        {
          name: 'color',
          type: 'TextColor',
          required: false,
          defaultValue: "'primary'",
          deprecated: false,
          description: 'Semantic OKLCH content color token.',
        },
        {
          name: 'align',
          type: 'TextAlign',
          required: false,
          defaultValue: "'start'",
          deprecated: false,
          description: 'Text alignment using logical properties (start/end for RTL compatibility).',
        },
        {
          name: 'truncate',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Truncate overflowing text on a single line with ellipsis.',
        },
        {
          name: 'lineClamp',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum number of lines to display before truncating.',
        },
        {
          name: 'slot',
          type: 'string | ',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Slot identifier used for composition with React Aria components.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Children content to render inside the text element.',
        },
      ],
    },
  ],
  inputField: [
    {
      componentName: 'InputField',
      title: 'InputField Props',
      component: '<InputField />',
      description: 'Root wrapper and shorthand single-component interface for input fields',
      props: [
        {
          name: 'id',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Explicit input element ID. Overrides auto-generated ID.',
        },
        {
          name: 'name',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Form control name for HTML form submission and form libraries.',
        },
        {
          name: 'variant',
          type: 'InputFieldVariant',
          required: false,
          defaultValue: "'outline'",
          deprecated: false,
          description: 'Visual style variant of the input surface.',
        },
        {
          name: 'labelVariant',
          type: 'InputFieldLabelVariant',
          required: false,
          defaultValue: "'default'",
          deprecated: false,
          description: 'Positioning and behavior variant of the label.',
        },
        {
          name: 'size',
          type: 'InputFieldSize',
          required: false,
          defaultValue: "'md'",
          deprecated: false,
          description: 'Size scale of the input field.',
        },
        {
          name: 'shadow',
          type: 'InputFieldShadow | boolean',
          required: false,
          defaultValue: "'none' (or 'sm' when variant=\"shadow\")",
          deprecated: false,
          description: 'Shadow elevation scale of the input field surface.',
        },
        {
          name: 'isDisabled',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the field as disabled. Propagated to all sub-components via context.',
        },
        {
          name: 'isReadOnly',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the field as read-only.',
        },
        {
          name: 'isRequired',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Marks the field as required. Adds `required` to the input and visual asterisk indicator.',
        },
        {
          name: 'isInvalid',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Marks the field as invalid. Shows `InputFieldError`, hides `InputFieldDescription`.',
        },
        {
          name: 'label',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Label text or node rendered when used as a single component.',
        },
        {
          name: 'placeholder',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Native placeholder text rendered when used as a single component.',
        },
        {
          name: 'description',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Helper description text rendered when used as a single component.',
        },
        {
          name: 'errorMessage',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Error message text rendered when `isInvalid` is true in single component usage.',
        },
        {
          name: 'startContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Element rendered before the input (e.g. decorative icon).',
        },
        {
          name: 'endContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Element rendered after the input (e.g. decorative icon).',
        },
        {
          name: 'value',
          type: 'string | number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Current value of the input when used as a single component.',
        },
        {
          name: 'defaultValue',
          type: 'string | number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Initial uncontrolled value of the input when used as a single component.',
        },
        {
          name: 'type',
          type: 'HTMLInputTypeAttribute',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: "Input element HTML type (e.g. 'text', 'email', 'password', 'number').",
        },
        {
          name: 'autoComplete',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            "Browser autofill / autocomplete attribute (e.g. 'email', 'current-password', 'given-name').",
        },
        {
          name: 'inputMode',
          type: "InputHTMLAttributes<HTMLInputElement>['inputMode']",
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            "Virtual keyboard hint for mobile browsers (e.g. 'numeric', 'decimal', 'email', 'tel').",
        },
        {
          name: 'maxLength',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum character count allowed in the native input.',
        },
        {
          name: 'minLength',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Minimum character count required in the native input.',
        },
        {
          name: 'pattern',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Regex pattern string for native HTML form validation.',
        },
        {
          name: 'min',
          type: 'number | string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Minimum value allowed for numeric/date input types.',
        },
        {
          name: 'max',
          type: 'number | string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum value allowed for numeric/date input types.',
        },
        {
          name: 'step',
          type: 'number | string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Granular step increment for numeric input types.',
        },
        {
          name: 'autoFocus',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Automatically focuses the input element when mounted.',
        },
        {
          name: 'inputRef',
          type: 'Ref<HTMLInputElement>',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Ref forwarded directly to the underlying native `<input>` element when using shorthand usage.',
        },
        {
          name: 'inputFilter',
          type: 'InputFieldInputFilter',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            "Character input filter restricting allowed entry ('numeric', 'decimal', 'alpha', 'alphanumeric').",
        },
        {
          name: 'classNames',
          type: 'InputFieldClassNames',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom CSS class names for individual slots (`root`, `label`, `wrapper`, `input`, `startContent`, `endContent`, `description`, `errorMessage`).',
        },
        {
          name: 'slotProps',
          type: 'InputFieldSlotProps',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom props for individual sub-component slots (`root`, `label`, `input`, `description`, `errorMessage`).',
        },
        {
          name: 'onChange',
          type: '(event: ChangeEvent<HTMLInputElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Change event handler when used as a single component.',
        },
        {
          name: 'onFocus',
          type: '(event: FocusEvent<HTMLInputElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Focus event handler when used as a single component.',
        },
        {
          name: 'onBlur',
          type: '(event: FocusEvent<HTMLInputElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Blur event handler when used as a single component.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'style',
          type: 'CSSProperties',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Inline styles applied to the root wrapper element.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Sub-components (compound pattern) OR omit for single-component shorthand pattern.',
        },
      ],
    },
    {
      componentName: 'InputField.Label',
      title: 'InputField Label Props',
      component: '<InputField.Label />',
      description: 'Label component for the input field',
      props: [
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Label content.',
        },
      ],
    },
    {
      componentName: 'InputField.Input',
      title: 'InputField Input Props',
      component: '<InputField.Input />',
      description: 'Native HTML input primitive wrapper',
      props: [
        {
          name: 'inputRef',
          type: 'Ref<HTMLInputElement>',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Ref forwarded directly to the native `<input>` element.',
        },
        {
          name: 'startContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Element rendered before the input (e.g. decorative icon, currency symbol). Note: Must be non-interactive/decorative only.',
        },
        {
          name: 'endContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Element rendered after the input (e.g. decorative icon). Note: Must be non-interactive/decorative only.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom CSS class names merged via `cn()` on the outer input wrapper `<div>`.',
        },
        {
          name: 'inputClassName',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()` on the native `<input>` element.',
        },
        {
          name: 'inputFilter',
          type: 'InputFieldInputFilter',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            "Character input filter restricting allowed entry ('numeric', 'decimal', 'alpha', 'alphanumeric').",
        },
      ],
    },
    {
      componentName: 'InputField.Description',
      title: 'InputField Description Props',
      component: '<InputField.Description />',
      description: 'Helper description text component for the input field',
      props: [
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Helper description content.',
        },
      ],
    },
    {
      componentName: 'InputField.Error',
      title: 'InputField Error Props',
      component: '<InputField.Error />',
      description: 'Error message text component for validation states',
      props: [
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Error message content.',
        },
      ],
    },
  ],
  checkbox: [
    {
      componentName: 'Checkbox',
      title: 'Checkbox Props',
      component: '<Checkbox />',
      description: 'Checkbox component supporting single, group, and custom icon usage',
      props: [
        {
          name: 'variant',
          type: 'CheckboxVariant',
          required: false,
          defaultValue: "'solid'",
          deprecated: false,
          description: 'Visual style variant of the checkbox indicator.',
        },
        {
          name: 'colorScheme',
          type: 'CheckboxColorScheme',
          required: false,
          defaultValue: "'primary'",
          deprecated: false,
          description: 'Color scheme applied to the checked/indeterminate state.',
        },
        {
          name: 'size',
          type: 'CheckboxSize',
          required: false,
          defaultValue: "'md'",
          deprecated: false,
          description: 'Size scale of the checkbox.',
        },
        {
          name: 'radius',
          type: 'CheckboxRadius',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            "Border radius corner shape of the checkbox indicator. Use 'none' for square or 'full' for circular checkboxes.",
        },
        {
          name: 'isSelected',
          type: 'boolean',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Controlled selected state.',
        },
        {
          name: 'defaultSelected',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Uncontrolled default selected state.',
        },
        {
          name: 'isIndeterminate',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Indeterminate state — used for parent checkboxes in a selection tree.',
        },
        {
          name: 'isDisabled',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the checkbox as disabled.',
        },
        {
          name: 'isReadOnly',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the checkbox as read-only.',
        },
        {
          name: 'isRequired',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the checkbox as required.',
        },
        {
          name: 'isInvalid',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the checkbox as invalid.',
        },
        {
          name: 'value',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Value used when inside a CheckboxGroup.',
        },
        {
          name: 'onChange',
          type: '(isSelected: boolean) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Change handler — receives the new boolean selected state.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()` on the root label element.',
        },
        {
          name: 'style',
          type: 'CSSProperties',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Inline styles applied to the root label element.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Visible label text rendered beside the indicator.',
        },
        {
          name: 'checkedIcon',
          type: 'ReactNode | ((props: { readonly className: string }) => ReactNode)',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom icon rendered when the checkbox is checked. Can be a ReactNode or a render function receiving `{ className: string }`.',
        },
        {
          name: 'uncheckedIcon',
          type: 'ReactNode | ((props: { readonly className: string }) => ReactNode)',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom icon rendered when the checkbox is unchecked. Can be a ReactNode or a render function receiving `{ className: string }`.',
        },
        {
          name: 'indeterminateIcon',
          type: 'ReactNode | ((props: { readonly className: string }) => ReactNode)',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Custom icon rendered when the checkbox is in an indeterminate state. Can be a ReactNode or a render function receiving `{ className: string }`.',
        },
      ],
    },
    {
      componentName: 'CheckboxGroup',
      title: 'CheckboxGroup Props',
      component: '<CheckboxGroup />',
      description: 'Group component managing selection state for child checkboxes',
      props: [
        {
          name: 'value',
          type: 'string[]',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Controlled array of selected values.',
        },
        {
          name: 'defaultValue',
          type: 'string[]',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Uncontrolled default selected values.',
        },
        {
          name: 'onChange',
          type: '(value: string[]) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Change handler — receives the new array of selected values.',
        },
        {
          name: 'variant',
          type: 'CheckboxVariant',
          required: false,
          defaultValue: "'solid'",
          deprecated: false,
          description: 'Visual style variant propagated to all child Checkboxes.',
        },
        {
          name: 'colorScheme',
          type: 'CheckboxColorScheme',
          required: false,
          defaultValue: "'primary'",
          deprecated: false,
          description: 'Color scheme propagated to all child Checkboxes.',
        },
        {
          name: 'size',
          type: 'CheckboxSize',
          required: false,
          defaultValue: "'md'",
          deprecated: false,
          description: 'Size scale propagated to all child Checkboxes.',
        },
        {
          name: 'radius',
          type: 'CheckboxRadius',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Border radius corner shape propagated to all child Checkboxes.',
        },
        {
          name: 'orientation',
          type: '"vertical" | "horizontal"',
          required: false,
          defaultValue: "'vertical'",
          deprecated: false,
          description: 'Layout direction of the checkbox group.',
        },
        {
          name: 'isDisabled',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks all checkboxes in the group as disabled.',
        },
        {
          name: 'isReadOnly',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks all checkboxes in the group as read-only.',
        },
        {
          name: 'isRequired',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Marks the group as required.',
        },
        {
          name: 'isInvalid',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Marks the group as invalid. Shows CheckboxGroupError, hides CheckboxGroupDescription.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names merged via `cn()`.',
        },
        {
          name: 'style',
          type: 'CSSProperties',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Inline styles applied to the root wrapper element.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          defaultValue: null,
          deprecated: false,
          description:
            'Sub-components: CheckboxGroupLabel, Checkbox[], CheckboxGroupDescription, CheckboxGroupError.',
        },
      ],
    },
  ],
  textarea: [
    {
      componentName: 'Textarea',
      title: 'Textarea Props',
      component: '<Textarea />',
      description:
        'Standalone shorthand and wrapper component for multi-line inputs with auto-resize, character counter, and variants',
      props: [
        {
          name: 'label',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Label content for the textarea.',
        },
        {
          name: 'description',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Helper description text rendered below the textarea.',
        },
        {
          name: 'errorMessage',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Error message text displayed when isInvalid is true.',
        },
        {
          name: 'variant',
          type: "InputFieldProps['variant']",
          required: false,
          defaultValue: "'outline'",
          deprecated: false,
          description: 'Visual surface styling variant.',
        },
        {
          name: 'labelVariant',
          type: "InputFieldProps['labelVariant']",
          required: false,
          defaultValue: "'default'",
          deprecated: false,
          description: 'Label positioning and floating behavior.',
        },
        {
          name: 'size',
          type: "InputFieldProps['size']",
          required: false,
          defaultValue: "'md'",
          deprecated: false,
          description: 'Size scale for the textarea.',
        },
        {
          name: 'shadow',
          type: "InputFieldProps['shadow']",
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Shadow elevation level.',
        },
        {
          name: 'isDisabled',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Whether the textarea is disabled.',
        },
        {
          name: 'isReadOnly',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Whether the textarea is in read-only mode.',
        },
        {
          name: 'isRequired',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Whether the textarea is marked as required.',
        },
        {
          name: 'isInvalid',
          type: 'boolean',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description: 'Whether the textarea is in an invalid/error state.',
        },
        {
          name: 'value',
          type: 'string | number | readonly string[]',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Controlled value of the textarea.',
        },
        {
          name: 'defaultValue',
          type: 'string | number | readonly string[]',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Default uncontrolled value of the textarea.',
        },
        {
          name: 'placeholder',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Placeholder text shown when the textarea is empty.',
        },
        {
          name: 'startContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Adornment content rendered at the start inside the textarea wrapper.',
        },
        {
          name: 'endContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Adornment content rendered at the end inside the textarea wrapper.',
        },
        {
          name: 'minRows',
          type: 'number',
          required: false,
          defaultValue: '3',
          deprecated: false,
          description: 'Minimum number of visible text rows.',
        },
        {
          name: 'maxRows',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum number of visible text rows before vertical scrolling kicks in.',
        },
        {
          name: 'autoResize',
          type: 'boolean',
          required: false,
          defaultValue: 'true',
          deprecated: false,
          description: 'Whether the textarea automatically resizes height based on content.',
        },
        {
          name: 'resize',
          type: 'TextareaResize',
          required: false,
          defaultValue: "'none'",
          deprecated: false,
          description: 'Directional resize handle control.',
        },
        {
          name: 'showCharacterCount',
          type: 'boolean | ((count: number, maxLength?: number) => ReactNode)',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Whether to display the character count (e.g. 24 / 200). Can be a boolean or a custom render function.',
        },
        {
          name: 'maxLength',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum number of characters allowed.',
        },
        {
          name: 'id',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Unique identifier for the textarea.',
        },
        {
          name: 'name',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Form field name for the textarea.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Additional CSS class name for the root container.',
        },
        {
          name: 'style',
          type: 'CSSProperties',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Inline styles for the root container.',
        },
        {
          name: 'classNames',
          type: 'TextareaClassNames',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom CSS class names for individual component slots.',
        },
        {
          name: 'slotProps',
          type: 'TextareaSlotProps',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Custom props for individual component slots.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description:
            'Compound subcomponent children (e.g. `<Textarea.Label>`, `<Textarea.Input>`).',
        },
        {
          name: 'onFocus',
          type: '(event: FocusEvent<HTMLTextAreaElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Focus event handler for the textarea element.',
        },
        {
          name: 'onBlur',
          type: '(event: FocusEvent<HTMLTextAreaElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Blur event handler for the textarea element.',
        },
        {
          name: 'onChange',
          type: '(event: ChangeEvent<HTMLTextAreaElement>) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Change event handler for the textarea element.',
        },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Callback fired when value changes, receiving the new text string.',
        },
      ],
    },
    {
      componentName: 'Textarea.Input',
      title: 'Textarea Input Props',
      component: '<Textarea.Input />',
      description: 'Multi-line textarea element component with auto-resize and counter features',
      props: [
        {
          name: 'startContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Adornment content rendered at the start inside the textarea wrapper.',
        },
        {
          name: 'endContent',
          type: 'ReactNode',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Adornment content rendered at the end inside the textarea wrapper.',
        },
        {
          name: 'minRows',
          type: 'number',
          required: false,
          defaultValue: '3',
          deprecated: false,
          description: 'Minimum number of visible text rows.',
        },
        {
          name: 'maxRows',
          type: 'number',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Maximum number of visible text rows before vertical scrolling kicks in.',
        },
        {
          name: 'autoResize',
          type: 'boolean',
          required: false,
          defaultValue: 'true',
          deprecated: false,
          description: 'Whether the textarea automatically resizes height based on content.',
        },
        {
          name: 'resize',
          type: 'TextareaResize',
          required: false,
          defaultValue: "'none'",
          deprecated: false,
          description: 'Directional resize handle control.',
        },
        {
          name: 'showCharacterCount',
          type: 'boolean | ((count: number, maxLength?: number) => ReactNode)',
          required: false,
          defaultValue: 'false',
          deprecated: false,
          description:
            'Whether to display the character count (e.g. 24 / 200). Can be a boolean or a custom render function.',
        },
        {
          name: 'textareaRef',
          type: 'Ref<HTMLTextAreaElement>',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Direct ref to the underlying native `<textarea>` element.',
        },
        {
          name: 'className',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Additional class names for the outer wrapper.',
        },
        {
          name: 'textareaClassName',
          type: 'string',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Additional class names applied directly to the native `<textarea>`.',
        },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          required: false,
          defaultValue: null,
          deprecated: false,
          description: 'Callback fired when value changes, receiving the new text string.',
        },
      ],
    },
  ],
};

export default propsDocumentation;
