name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/composite-actions/install

      - name: Build packages
        uses: ./.github/composite-actions/build

      - name: Publish to GitHub Packages
        run: pnpm publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
